services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: laststap
      POSTGRES_PASSWORD: lastPasswordForToDoList
      POSTGRES_DB: toDoList

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

